[project]
name = "cat in box"
required-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.0",
]

dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "ruff>=0.15.0",
]
